name: .NET Framework Desktop (VSTO Add-in Release)

on:
  push:
    tags:
      - 'v*'
      
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      
    - name: Install System.Text.Json to GAC
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
        ./nuget.exe install System.Text.Json -Version 8.0.5
        $gacutilPath = "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\"
        $env:PATH = "$gacutilPath;$env:PATH"
        gacutil /i System.Text.Json.8.0.5\lib\net462\System.Text.Json.dll

    - name: Build VSTO project
      run: |
        msbuild CrmOutlookAddIn\CrmOutlookAddIn.csproj /target:Publish /p:Configuration=Release /p:PublishDir=publish\

    - name: Archive publish folder
      run: |
        powershell -Command "Compress-Archive -Path CrmOutlookAddIn\publish\* -DestinationPath ClickOnceSetup.zip"

    - name: Upload build artifacts (optional)
      uses: actions/upload-artifact@v4
      with:
        name: ClickOnceSetup
        path: ClickOnceSetup.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ClickOnceSetup.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
