name: .NET Framework Desktop (VSTO Add-in)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      
    - name: Build VSTO project
      run: |
        msbuild CrmOutlookAddIn\CrmOutlookAddIn.csproj /p:Configuration=Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VSTO-Build
        path: CrmOutlookAddIn\bin\Release\
